/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.vushu.quickloader;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        //var res = QuickLoader.greet("Dan");
        //assertTrue(res.equals("Hi Dan"));

        MonkeyAppTest app = new MonkeyAppTest();
        //app.hej();
        app.start();







        //Library classUnderTest = new Library();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
